Repository smaddis/smad-deploy-azure, pull requests merged in 2021-03, with the labels that each got.

#26 Node count per tf workspace
  main.tf
  variables.tf
Labels: enhancement

#28 Github action for terraform
  .github/workflows/terraform-plan.yml
Labels: enhancement

#53 Modify action to use repo secrets
  .github/workflows/terraform-plan.yml
Labels: safe-to-run

#48 Bash scripts for testing hono
  tests/honoscript/README.md
  tests/honoscript/receiver.sh
  tests/honoscript/send.sh
  tests/honoscript/setup.sh
Labels: safe-to-test

#55 Lock Hono Helm chart version number
  modules/container_deployment/main.tf
Labels: safe-to-test
